language: go
sudo: true
go: 1.7
install:  npm cache clean -f && npm install -g n && n stable && node --version && npm install -g "gulpjs/gulp#4.0" && go get -v github.com/spf13/hugo
script: npm install && gulp build:prod
after_success: |
  if [ -n "$GITHUB_API_KEY" ] && [ ${TRAVIS_PULL_REQUEST} == "false" ] && [ $TRAVIS_BRANCH == "master" ]; then
    GIT_COMMIT=`git rev-parse --short HEAD`
    cd ./public

    git init > /dev/null 2>&1
    git add .
    git -c user.name='Travis-CI' -c user.email='travis@magnetic.io' commit -m "build ${GIT_COMMIT}" > /dev/null 2>&1
    echo "pushing content to gh-pages"
    git push --force --quiet "https://${GITHUB_API_KEY}@github.com/magneticio/revamp.io.git" master:gh-pages > /dev/null 2>&1
  fi
env:
  matrix:
    secure: FfbdoiVtyufEpar32b729jIai/7FLq/PeSTRg3kXWQxZJbemR+jBHUCsexf58X2byEESzQZNy6uMfZIJUgEvZaBrNUWmen8CJERHi0USSfH7x1/gXzUw1Xy8ze9/kMt3Qv6jmRf3xK2gi6T2oHMQPjnLgKgEBrZl7B8cRY3LHA+nl6gh+Q80cI/fp3n4BrOOBRQ4MkPgLGttlVcMIdGv/6KRBlosXb0v5WWZTcHTLMtaJ+lrcRDgZSIdQgc8BM6Fjcvxr5sFS5h0RXAvj2IPpKSiUO+M2x4R51YMDKMl7VOQK144d7xYP/1e/FP3cZS/ofE3WDuUzvutWLc3/TmUapAlWbUQBrn2PncAmX/i6VSTCBlINYKNbKdp1rUGgp8jIjNtJfgUTwzTfQtnwhYrZF+VxU4LWVr0zMn7kM4hoBVD/8YXA5K8fJ1XEWJrof4HInGNffue85wXFFmed/3n5p1XjKO0Zddxco0fT9o3ff3fzgcCEDCPA53QEjuGgxWD/WkaIqgmFLoxOGI1GBVXny8UvjClBpmYSOTFqEy/hcdTAI0jeudixdeXeOC8430GiLHjR+ClK4n5DKL9XbnFmYa3mSfqPaS/ETtg+AeVtjZ0c/7gpY/seBvI7WRAdz+itG1V2eAZulxghSdVsxwqSDNg5uxBuaKMPjiUq1Xtl4M=