# safelist
branches:
  only:
    - master

language: go
sudo: false
go: 1.7
node_js: 6.9.0
cache:
  directories:
  - /node_modules
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install v6.9.0
  - nvm use v6.9.0
  - npm install -g "gulpjs/gulp#4.0"
  - curl -sSL https://github.com/spf13/hugo/releases/download/v0.18.1/hugo_0.18.1_Linux-64bit.tar.gz | tar -zxf - -C /tmp/
  - mv /tmp/hugo_0.18.1_linux_amd64/hugo_0.18.1_linux_amd64 /tmp/hugo
  - rm -rf /tmp/hugo_0.18.1_linux_amd64
  - export PATH="/tmp:$PATH"
script: npm install && gulp build:prod
after_success: |
  if [ -n "$GITHUB_TOKEN" ] && [ ${TRAVIS_PULL_REQUEST} == "false" ] && [ $TRAVIS_BRANCH == "master" ]; then
    GIT_COMMIT=`git rev-parse --short HEAD`
    cd ./public && cp ../CNAME ./CNAME && cp ../robots.txt ./robots.txt
    git init > /dev/null 2>&1
    git add .
    git -c user.name='Travis-CI' -c user.email='travis@magnetic.io' commit -m "build ${GIT_COMMIT}" > /dev/null 2>&1
    echo "pushing content to gh-pages"
    git push --force --quiet "https://${GITHUB_TOKEN}@github.com/magneticio/vamp.io.git" master:gh-pages > /dev/null 2>&1
  fi