baseurl = "http://vamp.io"
languageCode = "en-us"
publishdir = "dist"
pluralizeListTitles = false
canonifyurls= true
title= "Vamp :: The Very Awesome Microservices Platform"
[blackfriday]
    plainIdAnchors = true
[permalinks]
    blog = "/:year/:month/:filename/"
[[menu.main]]
    name = "About Vamp"
    weight = 10
    identifier = "about-vamp"
    url = "/documentation"
[[menu.main]]
    name = "Installing Vamp"
    weight = 30
    identifier = "installation"
    url = "/installation/"    
[[menu.main]]
    name = "Using Vamp"
    weight = 40
    identifier = "using-vamp"
    url = "/documentation/using-vamp/"
[[menu.main]]
    name = "API reference"
    weight = 50
    identifier = "api-reference"
    url = "/documentation/api-reference/"
[[menu.main]]
    name = "CLI reference"
    weight = 60
    identifier = "cli-reference"
    url = "/documentation/cli-reference/"
[[menu.main]]
    name = "Guides"
    weight = 70
    identifier = "guides"
    url = "/documentation/guides/"               
[[menu.main]]
    name = "Community"
    weight = 80
    identifier = "community"
    url = "/documentation/community/"  