baseurl = "."
languageCode = "en-us"
title = "Vamp"
theme = "vamp-theme"
metadataformat = "yaml"
canonifyurls = true

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "magnetic.io"
	description = "Vamp - Deploy and manage microservices with power and ease."
	copyright = "Released under the Apache 2 license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/magneticio/vamp"

	version = "0.9.0"
	logo = "images/logo.svg"
	favicon = "images/logo.svg"

	permalink = "#"

	# Custom assets
	custom_css  = [
	  "stylesheets/dropdown.css"
	]
	custom_js   = [
	  "javascripts/lunr.min.js",
	  "javascripts/version.js"
	]

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "pink"
    	accent  = "pink"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"

[social]
	twitter = "magneticio"
	github  = "magneticio/vamp"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[[menu.main]]
	name   = "Why use Vamp?"
	url    = "/why-use-vamp/why-use-vamp/"
	identifier = "why-use-vamp-top"
	weight = 10

[[menu.main]]
	name   = "Documentation"
	url    = "/documentation/how-vamp-works/architecture-and-components/"
	weight = 20

[[menu.main]]
	name   = "Resources"
	url    = "/resources/downloads/"
	weight = 30

[[menu.main]]
	name   = "Support"
	url    = "/support/"
	weight = 40

# Why use vamp
[[menu.main]]
	name = "Use cases"
	url = "/why-use-vamp/use-cases/use-cases"
	parent = "why-use-vamp-top"
	weight = 10

[[menu.main]]
	name  = "Vamp compared to..."
	url   = "/why-use-vamp/vamp-compared-to/proxies-and-load-balancers/"
	parent = "why-use-vamp-top"
	weight = 30

[[menu.main]]
	name	= "How Vamp works"
	url = "/documentation/how-vamp-works/architecture-and-components/"
	parent = "Documentation"
	weight = 10

[[menu.main]]
	name = "Installation"
	url = "/documentation/installation/overview"
	parent = "Documentation"
	weight = 20

[[menu.main]]
	name = "Tutorials"
	url = "/documentation/tutorials/overview"
	parent = "Documentation"
	weight = 30

[[menu.main]]
	name = "Using Vamp"
	url = "documentation/using-vamp/artifacts"
	parent = "Documentation"
	weight = 40

[[menu.main]]
	name = "API"
	url = "/documentation/api/0.9.1/api-reference"
	parent = "Documentation"
	weight = 50

[[menu.main]]
	name = "CLI"
	url = "/documentation/cli/cli-reference/"
	parent = "Documentation"
	weight = 60

[[menu.main]]
	name = "Release notes"
	url = "/documentation/release-notes/version-0-9-1/"
	parent = "Documentation"
	weight = 70